"""Add owner and guest tables

Revision ID: 4156e5ad5c54
Revises: 
Create Date: 2024-07-23 21:53:46.500038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '4156e5ad5c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_participants')
    op.drop_table('user')
    op.drop_table('meeting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', mssql.DATETIMEOFFSET(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__meeting__3213E83F8F17A714')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__user__3213E83FB53DF2DA')
    )
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='FK__meeting_p__meeti__2A4B4B5E'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='FK__meeting_p__user___2B3F6F97'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id', name='PK__meeting___2C22FFDB8DF1E7DD')
    )
    # ### end Alembic commands ###
